name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc
    
    - name: Build FFI test library
      run: gcc -shared -fPIC -o tests/libmita_test.so tests/ffi_test_lib.c
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
